# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8anAONxcKbc2GH5fXWRanTh8KmEKrUr

Charger le ficher csv
"""

import pandas as pd

# Remplace 'nom_du_fichier.csv' par le nom réel de ton fichier
df = pd.read_csv('/content/drive/MyDrive/StudentPerformanceFactors.csv')

# Afficher les 5 premières lignes
print(df.head())

"""Exploration des données

1️⃣ Vérifier la structure du dataset
"""

# Informations générales sur les colonnes et leur type
print(df.info())

# Statistiques générales des colonnes numériques
print(df.describe())

"""2️⃣ Vérifier les valeurs manquantes"""

print(df.isnull().sum())

"""3️⃣ Vérifier les valeurs uniques des variables catégorielles"""

# Liste des valeurs uniques dans chaque colonne catégorielle
for col in df.select_dtypes(include=['object']).columns:
    print(f"{col}: {df[col].unique()}")

"""# Clean"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# 1️⃣ Charger le dataset depuis Google Drive
file_path = "/content/drive/MyDrive/StudentPerformanceFactors.csv"  # Chemin correct
df = pd.read_csv(file_path)

# 2️⃣ Supprimer les doublons
df.drop_duplicates(inplace=True)

# 3️⃣ Remplir les valeurs manquantes
# Pour les colonnes numériques, on remplit avec la moyenne
df = df.fillna(df.mean(numeric_only=True))

# Pour les colonnes catégorielles, on remplit avec la valeur la plus fréquente (mode)
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].fillna(df[col].mode()[0])

# 4️⃣ Encoder les variables catégorielles
for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

# 5️⃣ Gérer les valeurs extrêmes (outliers)
def handle_outliers(df):
    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
    for col in numeric_cols:
        # Calculer le premier et troisième quartile, ainsi que l'IQR (Interquartile Range)
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1

        # Calcul des bornes pour identifier les outliers
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Remplacer les outliers par les bornes (ou utiliser la médiane, à ajuster selon votre préférence)
        if col == 'Tutoring_Sessions':  # Traitement spécifique pour la colonne 'Tutoring_Sessions'
            median_value = df[col].median()  # Calcul de la médiane
            df[col] = df[col].apply(lambda x: median_value if x < lower_bound or x > upper_bound else x)
        else:
            df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)

        # Identifier et afficher les outliers
        outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
        print(f"🔍 Valeurs extrêmes dans la colonne '{col}' : {len(outliers)} outliers détectés.")
    return df

df = handle_outliers(df)

# 6️⃣ Conversion explicite des colonnes numériques en 'int' ou 'float'
for col in df.select_dtypes(include=['int64', 'float64']).columns:
    try:
        # Si la colonne est float64, on peut l'arrondir et la convertir en int64
        if df[col].dtype == 'float64':
            df[col] = df[col].round().astype('int64')  # Arrondir et convertir en int64
        else:
            df[col] = pd.to_numeric(df[col], errors='raise')  # Conversion explicite
    except ValueError:
        print(f"Erreur lors de la conversion de la colonne {col} en numérique.")

# 7️⃣ Sauvegarder le dataset nettoyé
cleaned_file_path = "/content/drive/MyDrive/Cleaned_student-performance.csv"
df.to_csv(cleaned_file_path, index=False)
print(f"✅ Dataset nettoyé enregistré sous : {cleaned_file_path}")

from google.colab import files
files.download('/content/drive/MyDrive/Cleaned_student-performance.csv')

"""*Verification*"""

# Vérification des doublons, des valeurs manquantes, des types de données et des outliers

# Vérification des doublons
def check_duplicates(df):
    duplicates = df[df.duplicated()]
    if not duplicates.empty:
        print(f"🔴 Il y a {len(duplicates)} doublons dans le dataset.")
    else:
        print("🟢 Aucun doublon trouvé dans le dataset.")

check_duplicates(df)

# Vérification des valeurs manquantes
def check_missing_values(df):
    missing = df.isnull().sum()
    if missing.any():
        print("🔴 Valeurs manquantes détectées :")
        print(missing[missing > 0])
    else:
        print("🟢 Aucune valeur manquante détectée dans le dataset.")

check_missing_values(df)

# Vérification des types de données
def check_data_types(df):
    print("📝 Types de données des colonnes :")
    print(df.dtypes)
    # Vérifier que toutes les colonnes sont du type 'int' ou 'float' (selon tes besoins)
    if df.dtypes.value_counts().get('int64', 0) == df.shape[1]:
        print("🟢 Toutes les colonnes sont de type 'int64'.")
    else:
        print("🔴 Attention, certaines colonnes ne sont pas de type 'int64'.")

check_data_types(df)

# Vérification des valeurs extrêmes (outliers) dans le dataset
def check_outliers(df):
    print("📊 Vérification des valeurs extrêmes (outliers) :")
    numeric_cols = df.select_dtypes(include=['int64']).columns
    for col in numeric_cols:
        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
        print(f"🔍 Valeurs extrêmes dans la colonne '{col}' : {len(outliers)} outliers détectés.")

check_outliers(df)

"""1. Analyse exploratoire des données (EDA) :

affichage plus stati
"""

# Afficher les premières lignes du dataset
df.head()
# Statistiques descriptives pour les données numériques
df.describe()

"""Vérification de la corrélation"""

import matplotlib.pyplot as plt
import seaborn as sns

# Matrice de corrélation
corr_matrix = df.corr()

# Afficher la heatmap de la corrélation
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title("Matrice de corrélation")
plt.show()

"""1.4 Visualisation de la distribution des variables numériques"""

# Histogrammes pour visualiser la distribution des variables numériques
df.hist(figsize=(12, 10), bins=20)
plt.tight_layout()
plt.show()

# Boxplots pour détecter les outliers
for col in df.select_dtypes(include=['int64', 'float64']).columns:
    plt.figure(figsize=(8, 6))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot de {col}")
    plt.show()

"""1.5 Vérification des données manquantes (si applicable)

"""

# Vérification des valeurs manquantes
missing_values = df.isnull().sum()
print(f"Valeurs manquantes par colonne:\n{missing_values}")

"""Étape 2 : Préparation des données pour le modèle

> Add blockquote

2.1 Sélection des variables et de la cible
"""

# Séparation des variables indépendantes (X) et de la cible (y)
X = df.drop(columns=['Exam_Score'])  # Variables indépendantes
y = df['Exam_Score']  # Variable cible (performance des étudiants)

"""2.2 Diviser les données en ensembles d'entraînement et de test



"""

from sklearn.model_selection import train_test_split

# Diviser les données en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Afficher la taille des ensembles pour vérifier
print(f"Taille de l'ensemble d'entraînement : {X_train.shape}")
print(f"Taille de l'ensemble de test : {X_test.shape}")

"""2.3 Normalisation des données (facultatif mais recommandé)"""

from sklearn.preprocessing import StandardScaler

# Normaliser les données (entrainement et test)
scaler = StandardScaler()

# Ajuster le scaler sur les données d'entraînement et transformer les données d'entraînement
X_train_scaled = scaler.fit_transform(X_train)

# Transformer les données de test en utilisant le même scaler
X_test_scaled = scaler.transform(X_test)

# Vérification de la normalisation
print(f"Exemple de données normalisées (X_train_scaled) : \n{X_train_scaled[:5]}")

"""Étape 1 : Appliquer l'algorithme K-means



"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, silhouette_samples

# ========= Préparation des données =========
# On suppose que X_train_scaled (données normalisées) et y_train (les cibles) sont déjà définis.
# Exemple si besoin :
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)

# ========= Réduction de dimension avec PCA =========
# On réduit à 2 dimensions pour faciliter le clustering et la visualisation
pca = PCA(n_components=2, random_state=42)
X_train_pca = pca.fit_transform(X_train_scaled)

# ========= Recherche du meilleur nombre de clusters =========
silhouette_scores = []
k_values = range(2, 7)
for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=50)
    kmeans.fit(X_train_pca)
    score = silhouette_score(X_train_pca, kmeans.labels_)
    silhouette_scores.append(score)
    print(f"k = {k} -> Score de silhouette = {score:.2f}")

plt.figure(figsize=(8,6))
plt.plot(list(k_values), silhouette_scores, marker='o', linestyle='-', color='blue')
plt.title("Score de Silhouette pour différents nombres de clusters")
plt.xlabel("Nombre de clusters")
plt.ylabel("Score de Silhouette")
plt.grid(True)
plt.show()

best_k = list(k_values)[np.argmax(silhouette_scores)]
print(f"Le meilleur nombre de clusters est : {best_k}")

# ========= Application finale de K-means avec le meilleur k =========
kmeans_final = KMeans(n_clusters=best_k, random_state=42, n_init=50)
kmeans_final.fit(X_train_pca)
silhouette_final = silhouette_score(X_train_pca, kmeans_final.labels_)
print(f"Score de silhouette pour {best_k} clusters : {silhouette_final:.2f}")

# ========= Visualisation des clusters =========
plt.figure(figsize=(8,6))
plt.scatter(X_train_pca[:, 0], X_train_pca[:, 1],
            c=kmeans_final.labels_, cmap='viridis', alpha=0.7)
plt.title(f"Clustering K-means (k={best_k}) après PCA")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.colorbar(label='Cluster')
plt.show()

# ========= Visualisation des centroids =========
centers_final = kmeans_final.cluster_centers_
plt.figure(figsize=(8,6))
plt.scatter(X_train_pca[:, 0], X_train_pca[:, 1],
            c=kmeans_final.labels_, cmap='viridis', alpha=0.6)
plt.scatter(centers_final[:, 0], centers_final[:, 1],
            c='red', marker='X', s=200, label='Centroids')
plt.title(f"Centroids des clusters (k={best_k})")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend()
plt.show()


# Ajout des labels finaux au DataFrame pour une analyse plus poussée
df_clustered_final = pd.DataFrame(X_train_pca, columns=['PC1', 'PC2'])
df_clustered_final['Cluster'] = kmeans_final.labels_
df_clustered_final['Exam_Score'] = y_train.values
print("Moyennes des caractéristiques pour chaque cluster (best_k) :")
print(df_clustered_final.groupby('Cluster').mean())

"""Étape 2 : Appliquer l'algorithme APRIORI"""

print(df.head())  # Aperçu des 5 premières lignes
print(df.info())  # Informations sur les types de données
print(df.describe())  # Statistiques générales
print(df.isnull().sum())  # Vérification des valeurs manquantes

"""✅ Analyse de tes données pour Apriori

🔥 Première tâche pour toi : Transformer tes données

---
"""

import pandas as pd

# Charger tes données
df = pd.read_csv("/content/drive/MyDrive/Cleaned_student-performance.csv")  # Si tu as un fichier CSV

# Transformation des variables continues en catégories
df['Étudie beaucoup'] = df['Hours_Studied'].apply(lambda x: 1 if x > 20 else 0)
df['Présence élevée'] = df['Attendance'].apply(lambda x: 1 if x > 80 else 0)
df['Bon élève'] = df['Previous_Scores'].apply(lambda x: 1 if x > 70 else 0)

# Encodage des variables catégoriques
df = pd.get_dummies(df, columns=['Motivation_Level', 'Parental_Involvement'])

# Suppression des colonnes inutiles
df = df.drop(columns=['Hours_Studied', 'Attendance', 'Previous_Scores'])

# Afficher l'aperçu des nouvelles données
print(df.head())

from mlxtend.frequent_patterns import apriori, association_rules
import networkx as nx
import matplotlib.pyplot as plt

# --- Préparation pour Apriori ---
# Convertir toutes les colonnes booléennes en entiers (0 et 1)
for col in df.columns:
    if df[col].dtype == 'bool':
        df[col] = df[col].astype(int)

# Liste des colonnes binaires pertinentes pour Apriori
binary_cols = [
    'Étudie beaucoup', 'Présence élevée', 'Bon élève',
    'Motivation_Level_0', 'Motivation_Level_1', 'Motivation_Level_2',
    'Parental_Involvement_0', 'Parental_Involvement_1', 'Parental_Involvement_2'
]

# Créer le DataFrame pour Apriori
df_apriori = df[binary_cols]

# Convertir le DataFrame en booléen pour améliorer la performance et éviter l'avertissement
df_apriori = df_apriori.astype(bool)

# --- Application de l'algorithme Apriori ---
# Générer les ensembles fréquents avec un support minimum
frequent_itemsets = apriori(df_apriori, min_support=0.05, use_colnames=True)

# Extraire les règles d'association en utilisant le lift comme métrique
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)

# Afficher les 10 règles d'association avec le plus de lift, triées par ordre décroissant
print("Les 10 règles d'association avec le plus de lift:")
print(rules.sort_values(by='lift', ascending=False).head(10))

# --- Visualisation des règles d'association sous forme de graphe ---
# Créer un graphe orienté pour représenter les règles
G = nx.DiGraph()
for idx, row in rules.iterrows():
    for antecedent in row['antecedents']:
        for consequent in row['consequents']:
            G.add_edge(antecedent, consequent, weight=row['lift'])

# Dessiner le graphe
plt.figure(figsize=(10, 6))
pos = nx.spring_layout(G, seed=42)
nx.draw(G, pos, with_labels=True, node_color='lightblue', edge_color='gray',
        node_size=2000, font_size=10)
plt.title("Graphique des règles d'association")
plt.show()

# --- Exportation des règles d'association ---
rules.to_csv("regles_association.csv", index=False)
print("Les règles d'association ont été exportées dans 'regles_association.csv'")

"""Étape 3 : Appliquer l'algorithme KNN

1. Création d'une variable cible catégorielle

1.   List item
2.   List item
"""

import pandas as pd

# Charger le dataset nettoyé
df = pd.read_csv("/content/drive/MyDrive/Cleaned_student-performance.csv")

# Créer une nouvelle colonne "Score_Category"
df['Score_Category'] = df['Exam_Score'].apply(lambda x: 'High' if x >= 67 else 'Low')

# Afficher un aperçu
print(df[['Exam_Score', 'Score_Category']].head())

"""2. Préparation des données pour K-NN"""

from sklearn.model_selection import train_test_split

# On choisit certaines colonnes pertinentes pour la prédiction.
# Tu peux ajuster cette sélection selon ton analyse.
features = df.drop(columns=['Exam_Score', 'Score_Category'])
target = df['Score_Category']

# Diviser en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=42)

print(f"Taille de l'ensemble d'entraînement : {X_train.shape}")
print(f"Taille de l'ensemble de test : {X_test.shape}")

"""3. Normalisation des données

"""

from sklearn.preprocessing import StandardScaler

scaler_knn = StandardScaler()
X_train_scaled = scaler_knn.fit_transform(X_train)
X_test_scaled = scaler_knn.transform(X_test)

"""4. Application de K-NN et évaluation"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Créer le modèle K-NN avec un nombre de voisins initial (par exemple k=5)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

# Prédire sur l'ensemble de test
y_pred = knn.predict(X_test_scaled)

# Évaluer le modèle
accuracy = accuracy_score(y_test, y_pred)
print(f"Exactitude du modèle K-NN : {accuracy:.2f}")

print("Matrice de confusion:")
print(confusion_matrix(y_test, y_pred))

print("Rapport de classification:")
print(classification_report(y_test, y_pred))

"""5. Optimisation du paramètre k (nombre de voisins)





"""

import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score

k_values = range(1, 21)
cv_scores = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    # Utilisation de la validation croisée à 5 plis sur l'ensemble d'entraînement
    scores = cross_val_score(knn, X_train_scaled, y_train, cv=5, scoring='accuracy')
    cv_scores.append(scores.mean())

# Afficher les scores de validation pour chaque k
plt.figure(figsize=(8,6))
plt.plot(k_values, cv_scores, marker='o', linestyle='-', color='blue')
plt.xlabel('Nombre de voisins (k)')
plt.ylabel('Score moyen de validation croisée')
plt.title('Validation croisée pour K-NN')
plt.grid(True)
plt.show()

best_k = k_values[cv_scores.index(max(cv_scores))]
print(f"Le meilleur nombre de voisins (k) est : {best_k}")

"""réentraîner ton modèle avec ce meilleur k"""

# Réentraîner le modèle K-NN avec le meilleur k
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train_scaled, y_train)

# Évaluer sur l'ensemble de test
y_pred_best = knn_best.predict(X_test_scaled)
best_accuracy = accuracy_score(y_test, y_pred_best)
print(f"Exactitude du modèle K-NN optimisé (k={best_k}) : {best_accuracy:.2f}")

from sklearn.metrics import confusion_matrix
import seaborn as sns

# Calcul de la matrice de confusion
cm = confusion_matrix(y_test, y_pred)

# Visualisation de la matrice de confusion
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Bas', 'Moyenne', 'Haut'], yticklabels=['Bas', 'Moyenne', 'Haut'])
plt.title('Matrice de Confusion - K-NN')
plt.xlabel('Prédiction')
plt.ylabel('Réalité')
plt.show()

print("Rapport de classification:")
print(classification_report(y_test, y_pred))